services:
  neo4j:
    image: neo4j:community
    container_name: neo4j-dev
    environment:
      - NEO4J_AUTH=neo4j/thisIsLocalSoPasswordsDontMatter
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
  minio:
    image: minio/minio:latest
    container_name: minio-dev
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: thisIsLocalSoPasswordsDontMatter
    ports:
      - "9000:9000"  # MinIO Console
      - "9001:9001"  # MinIO Admin Console
    volumes:
      - minio_data:/data  # Persistent data storage
      - minio_config:/root/.minio  # Configuration
    command: server /data --console-address ":9001"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  minio_data:
  minio_config: