name: Build and push images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/monster-gen-frontend:latest ./frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/monster-gen-frontend:latest ${{ secrets.DOCKER_USERNAME }}/monster-gen-frontend:${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/monster-gen-backend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/monster-gen-backend:latest ${{ secrets.DOCKER_USERNAME }}/monster-gen-backend:${{ github.sha }}

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/monster-gen-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/monster-gen-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/monster-gen-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/monster-gen-backend:${{ github.sha }}